# Generated by Django 4.1 on 2025-05-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Classificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nutriente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("categoria", models.CharField(blank=True, max_length=255, null=True)),
                ("unidade", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ComposicaoAlimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "alimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alimentos.alimento",
                    ),
                ),
                (
                    "nutriente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alimentos.nutriente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alimento",
            name="classificacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="alimentos.classificacao",
            ),
        ),
    ]
