# Generated by Django 4.1 on 2025-07-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimento",
            name="ed",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="ms",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="pb",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
