# Generated by Django 4.1 on 2025-05-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]