# Generated by Django 4.1 on 2025-07-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0002_alter_alimento_ed_alter_alimento_ms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composicaoalimento",
            name="valor",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
    ]
