# Generated by Django 4.1 on 2025-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_alimento_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificacao',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
