# Generated by Django 4.1 on 2025-07-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0003_alter_composicaoalimento_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composicaoalimento",
            name="valor",
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=11),
        ),
    ]
