# Generated by Django 4.1 on 2025-06-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0004_nutriente_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composicaoalimento',
            old_name='valor',
            new_name='quantidade',
        ),
    ]
