# Generated by Django 4.1 on 2025-06-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0005_alimento_ed_alimento_ms_alimento_pb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimento",
            name="ed",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="ms",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="pb",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
