# Generated by Django 4.1 on 2025-06-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0005_rename_valor_composicaoalimento_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composicaoalimento',
            old_name='quantidade',
            new_name='valor',
        ),
    ]
