# Generated by Django 4.1 on 2025-06-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0006_rename_quantidade_composicaoalimento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='ed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='ms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='pb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='composicaoalimento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
