# Generated by Django 4.1 on 2025-06-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0006_alter_alimento_ed_alter_alimento_ms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimento",
            name="ed",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="ms",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="pb",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
