# Generated by Django 4.1 on 2025-06-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0007_alter_alimento_ed_alter_alimento_ms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutriente",
            name="categoria",
            field=models.CharField(default="Não categorizado", max_length=255),
        ),
    ]
