# Generated by Django 4.1 on 2025-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicaoexigencia',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
