# Generated by Django 4.1 on 2025-07-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exigencias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaanimal",
            name="esforco",
            field=models.CharField(default="Sem esforço", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="categoriaanimal",
            name="fase",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="categoriaanimal",
            name="gmd",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="categoriaanimal",
            name="peso_vivo",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
