# Generated by Django 4.1 on 2025-07-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exigencias", "0002_alter_categoriaanimal_esforco_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaanimal",
            name="fase",
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
