# Generated by Django 4.1 on 2025-07-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exigencias", "0003_alter_categoriaanimal_fase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaanimal",
            name="fase",
            field=models.IntegerField(default=0),
        ),
    ]
