# Generated by Django 4.1 on 2025-07-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exigencias", "0004_alter_categoriaanimal_fase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exigencia",
            name="ed",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="exigencia",
            name="pb",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
