# Generated by Django 4.1 on 2025-07-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exigencias", "0005_alter_exigencia_ed_alter_exigencia_pb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaanimal",
            name="esforco",
            field=models.CharField(default="Sem esforço", max_length=255),
        ),
    ]
